### ISSUE TITLE
Flickering Issue on start Camera.

### ISSUE THREAD

**Issue by rahul4452** [Parag2385/Picker#2]
Hello, 
Great work.
One thing really not looks good that when we start Camera there is a little flicker of previous activity is shown. I think it's just happening in the sample project but it's also the shows in my project.

Android Version: Pie(28)

**Comment by Parag2385** [comment]
Hello @rahul4452 

Thank you for testing it out and pointing out the issue. I never realized this flickering was there until you reported. So thank you.

I've solved it by disabling the animation while opening the Picker Activity, this seems to solve the problem:
```
    mPickerIntent.addFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION)
```

Have updated the lib, please use v1.0.4 and test it. And let me know the results.
